plugins {
    id 'com.gradleup.shadow'
}

loom {
    forge {
        mixinConfig "randomthings.mixins.json"
    }
}

architectury {
    platformSetupLoomIde()
    forge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    forge "net.minecraftforge:forge:$rootProject.forge_version"

    // Architectury API
    modImplementation "dev.architectury:architectury-forge:$rootProject.architectury_api_version"

    // JEI - API for compile, full mod for runtime testing
    modCompileOnly "mezz.jei:jei-$rootProject.minecraft_version-common-api:$rootProject.jei_version"
    modCompileOnly "mezz.jei:jei-$rootProject.minecraft_version-forge-api:$rootProject.jei_version"
    modLocalRuntime("mezz.jei:jei-$rootProject.minecraft_version-forge:$rootProject.jei_version") { transitive = false }

    common(project(path: ':common', configuration: 'namedElements')) { transitive = false }
    shadowBundle project(path: ':common', configuration: 'transformProductionForge')
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'mod_id', rootProject.mod_id
    inputs.property 'mod_name', rootProject.mod_name
    inputs.property 'mod_description', rootProject.mod_description
    inputs.property 'mod_author', rootProject.mod_author
    inputs.property 'license', rootProject.license
    inputs.property 'minecraft_version', rootProject.minecraft_version
    inputs.property 'forge_version', rootProject.forge_version.split('-')[1]

    filesMatching('META-INF/mods.toml') {
        expand(
            version: project.version,
            mod_id: rootProject.mod_id,
            mod_name: rootProject.mod_name,
            mod_description: rootProject.mod_description,
            mod_author: rootProject.mod_author,
            license: rootProject.license,
            minecraft_version: rootProject.minecraft_version,
            forge_version: rootProject.forge_version.split('-')[1]
        )
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}
