modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

displayURL="https://www.curseforge.com/minecraft/mc-mods/random-things"
authors="${mod_authors}"
issueTrackerURL="https://github.com/lumien231/Random-Things"

[[mods]]
modId="${mod_id}"
displayName="${mod_name}"
description="""${mod_description}"""
version="${mod_version}"



[[dependencies.randomthings]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.randomthings]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"