package lumien.randomthings.item;

import dev.architectury.registry.CreativeTabRegistry;
import dev.architectury.registry.registries.DeferredRegister;
import dev.architectury.registry.registries.RegistrySupplier;
import lumien.randomthings.block.BiomeStoneBlock;
import lumien.randomthings.block.ModBlocks;
import lumien.randomthings.lib.ModConstants;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.DyeColor;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;

/**
 * Item + creative-tab registry. Items (and {@code BlockItem}s) are added here as features are ported.
 *
 * <p>The Random Things creative tab is populated by a {@code displayItems} generator that iterates
 * the {@link #ITEMS} registry, so <em>every</em> registered item appears automatically — no per-item
 * tab tagging required.</p>
 */
public final class ModItems {

    public static final DeferredRegister<Item> ITEMS =
        DeferredRegister.create(ModConstants.MOD_ID, Registries.ITEM);

    public static final DeferredRegister<CreativeModeTab> TABS =
        DeferredRegister.create(ModConstants.MOD_ID, Registries.CREATIVE_MODE_TAB);

    public static final RegistrySupplier<CreativeModeTab> RT_CREATIVE_TAB = TABS.register("randomthings",
        () -> CreativeTabRegistry.create(builder -> {
            builder.title(Component.translatable("itemGroup.randomthings"));
            // Placeholder icon until FERTILIZED_DIRT is ported; replace then.
            builder.icon(() -> new ItemStack(Items.GRASS_BLOCK));
            builder.displayItems((params, output) -> {
                for (RegistrySupplier<Item> entry : ITEMS) {
                    // The Spectre Core is generated by the dimension, not player-obtainable
                    if ("spectre_core".equals(entry.getId().getPath())) {
                        continue;
                    }
                    output.accept(entry.get());
                }
            });
        }));

    // --- Group 1: redstone-themed blocks (BlockItems) ---
    public static final RegistrySupplier<BlockItem> ONLINE_DETECTOR = ITEMS.register("online_detector",
        () -> new BlockItem(ModBlocks.ONLINE_DETECTOR.get(), new Item.Properties()));

    public static final RegistrySupplier<BlockItem> REDSTONE_OBSERVER = ITEMS.register("redstone_observer",
        () -> new BlockItem(ModBlocks.REDSTONE_OBSERVER.get(), new Item.Properties()));

    public static final RegistrySupplier<BlockItem> BASIC_REDSTONE_INTERFACE = ITEMS.register("basic_redstone_interface",
        () -> new BlockItem(ModBlocks.BASIC_REDSTONE_INTERFACE.get(), new Item.Properties()));

    public static final RegistrySupplier<BlockItem> ENTITY_DETECTOR = ITEMS.register("entity_detector",
        () -> new BlockItem(ModBlocks.ENTITY_DETECTOR.get(), new Item.Properties()));

    // --- Group 1: redstone configuration tool & filters ---
    public static final RegistrySupplier<RedstoneToolItem> REDSTONE_TOOL = ITEMS.register("redstone_tool",
        () -> new RedstoneToolItem(new Item.Properties()));

    public static final RegistrySupplier<EntityFilterItem> ENTITY_FILTER = ITEMS.register("entity_filter",
        () -> new EntityFilterItem(new Item.Properties()));

    public static final RegistrySupplier<BlockItem> CHAT_DETECTOR = ITEMS.register("chat_detector",
        () -> new BlockItem(ModBlocks.CHAT_DETECTOR.get(), new Item.Properties()));

    public static final RegistrySupplier<BlockItem> GLOBAL_CHAT_DETECTOR = ITEMS.register("global_chat_detector",
        () -> new BlockItem(ModBlocks.GLOBAL_CHAT_DETECTOR.get(), new Item.Properties()));

    public static final RegistrySupplier<IdCardItem> ID_CARD = ITEMS.register("id_card",
        () -> new IdCardItem(new Item.Properties().stacksTo(1)));

    // --- Group 2: item-handling utility blocks (BlockItems) ---
    public static final RegistrySupplier<BlockItem> ITEM_COLLECTOR = ITEMS.register("item_collector",
        () -> new BlockItem(ModBlocks.ITEM_COLLECTOR.get(), new Item.Properties()));

    public static final RegistrySupplier<BlockItem> INVENTORY_REROUTER = ITEMS.register("inventory_rerouter",
        () -> new BlockItem(ModBlocks.INVENTORY_REROUTER.get(), new Item.Properties()));

    public static final RegistrySupplier<BlockItem> ADVANCED_ITEM_COLLECTOR = ITEMS.register("advanced_item_collector",
        () -> new BlockItem(ModBlocks.ADVANCED_ITEM_COLLECTOR.get(), new Item.Properties()));

    public static final RegistrySupplier<ItemFilterItem> ITEM_FILTER = ITEMS.register("item_filter",
        () -> new ItemFilterItem(new Item.Properties()));

    public static final RegistrySupplier<BlockItem> DYEING_MACHINE = ITEMS.register("dyeing_machine",
        () -> new BlockItem(ModBlocks.DYEING_MACHINE.get(), new Item.Properties()));

    // --- Group 3: crafting stations (BlockItems) ---
    public static final RegistrySupplier<BlockItem> IMBUING_STATION = ITEMS.register("imbuing_station",
        () -> new BlockItem(ModBlocks.IMBUING_STATION.get(), new Item.Properties()));

    public static final RegistrySupplier<BlockItem> CUSTOM_CRAFTING_TABLE_OAK = ITEMS.register("custom_crafting_table_oak",
        () -> new BlockItem(ModBlocks.CUSTOM_CRAFTING_TABLE_OAK.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> CUSTOM_CRAFTING_TABLE_SPRUCE = ITEMS.register("custom_crafting_table_spruce",
        () -> new BlockItem(ModBlocks.CUSTOM_CRAFTING_TABLE_SPRUCE.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> CUSTOM_CRAFTING_TABLE_BIRCH = ITEMS.register("custom_crafting_table_birch",
        () -> new BlockItem(ModBlocks.CUSTOM_CRAFTING_TABLE_BIRCH.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> CUSTOM_CRAFTING_TABLE_JUNGLE = ITEMS.register("custom_crafting_table_jungle",
        () -> new BlockItem(ModBlocks.CUSTOM_CRAFTING_TABLE_JUNGLE.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> CUSTOM_CRAFTING_TABLE_ACACIA = ITEMS.register("custom_crafting_table_acacia",
        () -> new BlockItem(ModBlocks.CUSTOM_CRAFTING_TABLE_ACACIA.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> CUSTOM_CRAFTING_TABLE_DARK_OAK = ITEMS.register("custom_crafting_table_dark_oak",
        () -> new BlockItem(ModBlocks.CUSTOM_CRAFTING_TABLE_DARK_OAK.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> CUSTOM_CRAFTING_TABLE_MANGROVE = ITEMS.register("custom_crafting_table_mangrove",
        () -> new BlockItem(ModBlocks.CUSTOM_CRAFTING_TABLE_MANGROVE.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> CUSTOM_CRAFTING_TABLE_CHERRY = ITEMS.register("custom_crafting_table_cherry",
        () -> new BlockItem(ModBlocks.CUSTOM_CRAFTING_TABLE_CHERRY.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> CUSTOM_CRAFTING_TABLE_BAMBOO = ITEMS.register("custom_crafting_table_bamboo",
        () -> new BlockItem(ModBlocks.CUSTOM_CRAFTING_TABLE_BAMBOO.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> CUSTOM_CRAFTING_TABLE_CRIMSON = ITEMS.register("custom_crafting_table_crimson",
        () -> new BlockItem(ModBlocks.CUSTOM_CRAFTING_TABLE_CRIMSON.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> CUSTOM_CRAFTING_TABLE_WARPED = ITEMS.register("custom_crafting_table_warped",
        () -> new BlockItem(ModBlocks.CUSTOM_CRAFTING_TABLE_WARPED.get(), new Item.Properties()));

    // --- Group 5: decorative / sound ---
    public static final RegistrySupplier<BlockItem> SOUND_BOX = ITEMS.register("sound_box",
        () -> new BlockItem(ModBlocks.SOUND_BOX.get(), new Item.Properties()));

    public static final RegistrySupplier<ItemSoundPattern> SOUND_PATTERN = ITEMS.register("sound_pattern",
        () -> new ItemSoundPattern());

    private static RegistrySupplier<ColoredGrassItem> grass(String name, DyeColor color) {
        return ITEMS.register(name,
            () -> new ColoredGrassItem(ModBlocks.COLORED_GRASS.get(), color, new Item.Properties()));
    }

    public static final RegistrySupplier<ColoredGrassItem> COLORED_GRASS_WHITE = grass("colored_grass_white", DyeColor.WHITE);
    public static final RegistrySupplier<ColoredGrassItem> COLORED_GRASS_ORANGE = grass("colored_grass_orange", DyeColor.ORANGE);
    public static final RegistrySupplier<ColoredGrassItem> COLORED_GRASS_MAGENTA = grass("colored_grass_magenta", DyeColor.MAGENTA);
    public static final RegistrySupplier<ColoredGrassItem> COLORED_GRASS_LIGHT_BLUE = grass("colored_grass_light_blue", DyeColor.LIGHT_BLUE);
    public static final RegistrySupplier<ColoredGrassItem> COLORED_GRASS_YELLOW = grass("colored_grass_yellow", DyeColor.YELLOW);
    public static final RegistrySupplier<ColoredGrassItem> COLORED_GRASS_LIME = grass("colored_grass_lime", DyeColor.LIME);
    public static final RegistrySupplier<ColoredGrassItem> COLORED_GRASS_PINK = grass("colored_grass_pink", DyeColor.PINK);
    public static final RegistrySupplier<ColoredGrassItem> COLORED_GRASS_GRAY = grass("colored_grass_gray", DyeColor.GRAY);
    public static final RegistrySupplier<ColoredGrassItem> COLORED_GRASS_LIGHT_GRAY = grass("colored_grass_light_gray", DyeColor.LIGHT_GRAY);
    public static final RegistrySupplier<ColoredGrassItem> COLORED_GRASS_CYAN = grass("colored_grass_cyan", DyeColor.CYAN);
    public static final RegistrySupplier<ColoredGrassItem> COLORED_GRASS_PURPLE = grass("colored_grass_purple", DyeColor.PURPLE);
    public static final RegistrySupplier<ColoredGrassItem> COLORED_GRASS_BLUE = grass("colored_grass_blue", DyeColor.BLUE);
    public static final RegistrySupplier<ColoredGrassItem> COLORED_GRASS_BROWN = grass("colored_grass_brown", DyeColor.BROWN);
    public static final RegistrySupplier<ColoredGrassItem> COLORED_GRASS_GREEN = grass("colored_grass_green", DyeColor.GREEN);
    public static final RegistrySupplier<ColoredGrassItem> COLORED_GRASS_RED = grass("colored_grass_red", DyeColor.RED);
    public static final RegistrySupplier<ColoredGrassItem> COLORED_GRASS_BLACK = grass("colored_grass_black", DyeColor.BLACK);

    // --- Group 6: player mechanics (Floo items) ---
    public static final RegistrySupplier<FlooPowderItem> FLOO_POWDER = ITEMS.register("floo_powder",
        () -> new FlooPowderItem(new Item.Properties()));

    public static final RegistrySupplier<FlooPouchItem> FLOO_POUCH = ITEMS.register("floo_pouch",
        () -> new FlooPouchItem(new Item.Properties()));

    public static final RegistrySupplier<FlooSignItem> FLOO_SIGN = ITEMS.register("floo_sign",
        () -> new FlooSignItem(new Item.Properties()));

    public static final RegistrySupplier<FlooTokenItem> FLOO_TOKEN = ITEMS.register("floo_token",
        () -> new FlooTokenItem(new Item.Properties()));

    // --- Group 4: spectre (self-contained subset) ---
    public static final RegistrySupplier<SpectreIngotItem> SPECTRE_INGOT = ITEMS.register("spectre_ingot",
        () -> new SpectreIngotItem(new Item.Properties()));

    public static final RegistrySupplier<SpectreStringItem> SPECTRE_STRING = ITEMS.register("spectre_string",
        () -> new SpectreStringItem(new Item.Properties()));

    public static final RegistrySupplier<BlockItem> SPECTRE_BLOCK = ITEMS.register("spectre_block",
        () -> new BlockItem(ModBlocks.SPECTRE_BLOCK.get(), new Item.Properties()));

    // --- Decorative / colored blocks (BlockItems) ---
    public static final RegistrySupplier<BlockItem> RAINBOW_LAMP = ITEMS.register("rainbow_lamp",
        () -> new BlockItem(ModBlocks.RAINBOW_LAMP.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> SUPER_LUBRICENT_STONE = ITEMS.register("super_lubricent_stone",
        () -> new BlockItem(ModBlocks.SUPER_LUBRICENT_STONE.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> LAPIS_GLASS = ITEMS.register("lapis_glass",
        () -> new BlockItem(ModBlocks.LAPIS_GLASS.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> QUARTZ_GLASS = ITEMS.register("quartz_glass",
        () -> new BlockItem(ModBlocks.QUARTZ_GLASS.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> BIOME_GLASS = ITEMS.register("biome_glass",
        () -> new BlockItem(ModBlocks.BIOME_GLASS.get(), new Item.Properties()));

    public static final RegistrySupplier<BiomeCrystalItem> BIOME_CRYSTAL = ITEMS.register("biome_crystal",
        () -> new BiomeCrystalItem(new Item.Properties()));

    public static final RegistrySupplier<BiomeStoneBlockItem> BIOME_STONE_SMOOTH = ITEMS.register("biome_stone_smooth",
        () -> new BiomeStoneBlockItem(ModBlocks.BIOME_STONE.get(), new Item.Properties(), BiomeStoneBlock.Variant.SMOOTH));
    public static final RegistrySupplier<BiomeStoneBlockItem> BIOME_STONE_COBBLE = ITEMS.register("biome_stone_cobble",
        () -> new BiomeStoneBlockItem(ModBlocks.BIOME_STONE.get(), new Item.Properties(), BiomeStoneBlock.Variant.COBBLE));
    public static final RegistrySupplier<BiomeStoneBlockItem> BIOME_STONE_BRICK = ITEMS.register("biome_stone_brick",
        () -> new BiomeStoneBlockItem(ModBlocks.BIOME_STONE.get(), new Item.Properties(), BiomeStoneBlock.Variant.BRICK));
    public static final RegistrySupplier<BiomeStoneBlockItem> BIOME_STONE_CRACKED = ITEMS.register("biome_stone_cracked",
        () -> new BiomeStoneBlockItem(ModBlocks.BIOME_STONE.get(), new Item.Properties(), BiomeStoneBlock.Variant.CRACKED));
    public static final RegistrySupplier<BiomeStoneBlockItem> BIOME_STONE_CHISELED = ITEMS.register("biome_stone_chiseled",
        () -> new BiomeStoneBlockItem(ModBlocks.BIOME_STONE.get(), new Item.Properties(), BiomeStoneBlock.Variant.CHISELED));

    // --- Redstone (no-block-entity) ---
    public static final RegistrySupplier<BlockItem> SIDED_REDSTONE = ITEMS.register("sided_redstone",
        () -> new BlockItem(ModBlocks.SIDED_REDSTONE.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> CONTACT_BUTTON = ITEMS.register("contact_button",
        () -> new BlockItem(ModBlocks.CONTACT_BUTTON.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> CONTACT_LEVER = ITEMS.register("contact_lever",
        () -> new BlockItem(ModBlocks.CONTACT_LEVER.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> ANALOG_EMITTER = ITEMS.register("analog_emitter",
        () -> new BlockItem(ModBlocks.ANALOG_EMITTER.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> ADVANCED_REDSTONE_TORCH = ITEMS.register("advanced_redstone_torch",
        () -> new net.minecraft.world.item.StandingAndWallBlockItem(
            ModBlocks.ADVANCED_REDSTONE_TORCH.get(), ModBlocks.ADVANCED_WALL_REDSTONE_TORCH.get(),
            new Item.Properties(), net.minecraft.core.Direction.DOWN));
    public static final RegistrySupplier<BlockItem> ADVANCED_REDSTONE_REPEATER = ITEMS.register("advanced_redstone_repeater",
        () -> new BlockItem(ModBlocks.ADVANCED_REDSTONE_REPEATER.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> IGNITER = ITEMS.register("igniter",
        () -> new BlockItem(ModBlocks.IGNITER.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> BLOCK_BREAKER = ITEMS.register("block_breaker",
        () -> new BlockItem(ModBlocks.BLOCK_BREAKER.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> IRON_DROPPER = ITEMS.register("iron_dropper",
        () -> new BlockItem(ModBlocks.IRON_DROPPER.get(), new Item.Properties()));

    // --- Standalone utility items ---
    public static final RegistrySupplier<EctoplasmItem> ECTOPLASM = ITEMS.register("ectoplasm", EctoplasmItem::new);
    public static final RegistrySupplier<LuminousPowderItem> LUMINOUS_POWDER = ITEMS.register("luminous_powder", LuminousPowderItem::new);
    public static final RegistrySupplier<PositionFilterItem> POSITION_FILTER = ITEMS.register("position_filter",
        () -> new PositionFilterItem(new Item.Properties()));
    public static final RegistrySupplier<MagicHoodItem> MAGIC_HOOD = ITEMS.register("magic_hood",
        () -> new MagicHoodItem(new Item.Properties()));
    public static final RegistrySupplier<ObsidianWaterWalkingBootsItem> OBSIDIAN_WATER_WALKING_BOOTS = ITEMS.register("obsidian_water_walking_boots",
        () -> new ObsidianWaterWalkingBootsItem(new Item.Properties()));
    public static final RegistrySupplier<SpectreKeyItem> SPECTRE_KEY =
        ITEMS.register("spectre_key", () -> new SpectreKeyItem(new Item.Properties()));
    public static final RegistrySupplier<BlockItem> SPECTRE_CORE = ITEMS.register("spectre_core",
        () -> new BlockItem(lumien.randomthings.block.ModBlocks.SPECTRE_CORE.get(), new Item.Properties()));

    public static final RegistrySupplier<StableEnderPearlItem> STABLE_ENDER_PEARL =
        ITEMS.register("stable_ender_pearl", StableEnderPearlItem::new);
    public static final RegistrySupplier<EnderBucketItem> ENDER_BUCKET =
        ITEMS.register("ender_bucket", EnderBucketItem::new);
    public static final RegistrySupplier<ReinforcedEnderBucketItem> REINFORCED_ENDER_BUCKET =
        ITEMS.register("reinforced_ender_bucket", ReinforcedEnderBucketItem::new);

    public static final RegistrySupplier<BlockItem> PLANT_CHEST = ITEMS.register("plant_chest",
        () -> lumien.randomthings.platform.Services.PLATFORM.createPlantChestItem(
            lumien.randomthings.block.ModBlocks.PLANT_CHEST.get(), new Item.Properties()));

    public static final RegistrySupplier<BlockItem> NATURE_CORE = ITEMS.register("nature_core",
        () -> new BlockItem(lumien.randomthings.block.ModBlocks.NATURE_CORE.get(), new Item.Properties()));

    public static final RegistrySupplier<BlockItem> RAIN_SHIELD = ITEMS.register("rain_shield",
        () -> new BlockItem(lumien.randomthings.block.ModBlocks.RAIN_SHIELD.get(), new Item.Properties()));

    public static final RegistrySupplier<PlayerInterfaceItem> PLAYER_INTERFACE = ITEMS.register("player_interface",
        () -> new PlayerInterfaceItem(ModBlocks.PLAYER_INTERFACE.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> BIOME_RADAR = ITEMS.register("biome_radar",
        () -> new BlockItem(ModBlocks.BIOME_RADAR.get(), new Item.Properties()));

    // --- Spectre energy network ---
    public static final RegistrySupplier<BlockItem> SPECTRE_COIL_NORMAL = ITEMS.register("spectre_coil_normal",
        () -> new BlockItem(ModBlocks.SPECTRE_COIL_NORMAL.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> SPECTRE_COIL_REDSTONE = ITEMS.register("spectre_coil_redstone",
        () -> new BlockItem(ModBlocks.SPECTRE_COIL_REDSTONE.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> SPECTRE_COIL_ENDER = ITEMS.register("spectre_coil_ender",
        () -> new BlockItem(ModBlocks.SPECTRE_COIL_ENDER.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> SPECTRE_COIL_NUMBER = ITEMS.register("spectre_coil_number",
        () -> new BlockItem(ModBlocks.SPECTRE_COIL_NUMBER.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> SPECTRE_COIL_GENESIS = ITEMS.register("spectre_coil_genesis",
        () -> new BlockItem(ModBlocks.SPECTRE_COIL_GENESIS.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> SPECTRE_ENERGY_INJECTOR = ITEMS.register("spectre_energy_injector",
        () -> new BlockItem(ModBlocks.SPECTRE_ENERGY_INJECTOR.get(), new Item.Properties()));
    public static final RegistrySupplier<SpectreAnchorItem> SPECTRE_ANCHOR = ITEMS.register("spectre_anchor",
        () -> new SpectreAnchorItem(new Item.Properties()));
    public static final RegistrySupplier<SpectreChargerItem> SPECTRE_CHARGER_NORMAL = ITEMS.register("spectre_charger_normal",
        () -> new SpectreChargerItem(SpectreChargerItem.Tier.NORMAL));
    public static final RegistrySupplier<SpectreChargerItem> SPECTRE_CHARGER_REDSTONE = ITEMS.register("spectre_charger_redstone",
        () -> new SpectreChargerItem(SpectreChargerItem.Tier.REDSTONE));
    public static final RegistrySupplier<SpectreChargerItem> SPECTRE_CHARGER_ENDER = ITEMS.register("spectre_charger_ender",
        () -> new SpectreChargerItem(SpectreChargerItem.Tier.ENDER));
    public static final RegistrySupplier<SpectreChargerItem> SPECTRE_CHARGER_GENESIS = ITEMS.register("spectre_charger_genesis",
        () -> new SpectreChargerItem(SpectreChargerItem.Tier.GENESIS));
    public static final RegistrySupplier<SpectreIlluminatorItem> SPECTRE_ILLUMINATOR = ITEMS.register("spectre_illuminator",
        () -> new SpectreIlluminatorItem(new Item.Properties()));
    public static final RegistrySupplier<BlazeAndSteelItem> BLAZE_AND_STEEL = ITEMS.register("blaze_and_steel",
        () -> new BlazeAndSteelItem(new Item.Properties()));
    public static final RegistrySupplier<EscapeRopeItem> ESCAPE_ROPE = ITEMS.register("escape_rope", EscapeRopeItem::new);
    public static final RegistrySupplier<SummoningPendulumItem> SUMMONING_PENDULUM = ITEMS.register("summoning_pendulum", SummoningPendulumItem::new);
    public static final RegistrySupplier<EvilTearItem> EVIL_TEAR = ITEMS.register("evil_tear", EvilTearItem::new);
    public static final RegistrySupplier<TimeInABottleItem> TIME_IN_A_BOTTLE = ITEMS.register("time_in_a_bottle",
        () -> new TimeInABottleItem(new Item.Properties()));
    public static final RegistrySupplier<ChunkAnalyzerItem> CHUNK_ANALYZER = ITEMS.register("chunk_analyzer",
        () -> new ChunkAnalyzerItem(new Item.Properties()));
    public static final RegistrySupplier<BlackoutPowderItem> BLACKOUT_POWDER = ITEMS.register("blackout_powder",
        BlackoutPowderItem::new);
    public static final RegistrySupplier<EmeraldCompassItem> EMERALD_COMPASS = ITEMS.register("emerald_compass",
        () -> new EmeraldCompassItem(new Item.Properties()));
    public static final RegistrySupplier<GoldenCompassItem> GOLDEN_COMPASS = ITEMS.register("golden_compass",
        () -> new GoldenCompassItem(new Item.Properties()));

    public static final RegistrySupplier<DiaphanousBlockItem> DIAPHANOUS_BLOCK = ITEMS.register("diaphanous_block",
        () -> new DiaphanousBlockItem(ModBlocks.DIAPHANOUS_BLOCK.get(), new Item.Properties()));

    // --- Sound subsystem ---
    public static final RegistrySupplier<BlockItem> SOUND_DAMPENER = ITEMS.register("sound_dampener",
        () -> new BlockItem(ModBlocks.SOUND_DAMPENER.get(), new Item.Properties()));
    public static final RegistrySupplier<ItemPortableSoundDampener> PORTABLE_SOUND_DAMPENER = ITEMS.register("portable_sound_dampener",
        ItemPortableSoundDampener::new);
    public static final RegistrySupplier<SoundRecorderItem> SOUND_RECORDER = ITEMS.register("sound_recorder",
        SoundRecorderItem::new);
    public static final RegistrySupplier<EclipsedClockItem> ECLIPSED_CLOCK = ITEMS.register("eclipsed_clock",
        () -> new EclipsedClockItem(new Item.Properties()));

    // --- Spectre tools ---
    public static final RegistrySupplier<SpectrePickaxeItem> SPECTRE_PICKAXE = ITEMS.register("spectre_pickaxe",
        () -> new SpectrePickaxeItem(new Item.Properties()));
    public static final RegistrySupplier<SpectreSwordItem> SPECTRE_SWORD = ITEMS.register("spectre_sword",
        () -> new SpectreSwordItem(new Item.Properties()));
    public static final RegistrySupplier<SpectreShovelItem> SPECTRE_SHOVEL = ITEMS.register("spectre_shovel",
        () -> new SpectreShovelItem(new Item.Properties()));
    public static final RegistrySupplier<SpectreAxeItem> SPECTRE_AXE = ITEMS.register("spectre_axe",
        () -> new SpectreAxeItem(new Item.Properties()));

    // --- Weather eggs ---
    public static final RegistrySupplier<WeatherEggItem> WEATHER_EGG_SUN = ITEMS.register("weather_egg_sun",
        () -> new WeatherEggItem(WeatherEggItem.WeatherType.SUN, new Item.Properties().stacksTo(16)));
    public static final RegistrySupplier<WeatherEggItem> WEATHER_EGG_RAIN = ITEMS.register("weather_egg_rain",
        () -> new WeatherEggItem(WeatherEggItem.WeatherType.RAIN, new Item.Properties().stacksTo(16)));
    public static final RegistrySupplier<WeatherEggItem> WEATHER_EGG_STORM = ITEMS.register("weather_egg_storm",
        () -> new WeatherEggItem(WeatherEggItem.WeatherType.STORM, new Item.Properties().stacksTo(16)));

    // --- Plants ---
    public static final RegistrySupplier<BlockItem> BLOOD_ROSE = ITEMS.register("blood_rose",
        () -> new BlockItem(ModBlocks.BLOOD_ROSE.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> GLOWING_MUSHROOM = ITEMS.register("glowing_mushroom",
        () -> new BlockItem(ModBlocks.GLOWING_MUSHROOM.get(), new Item.Properties()));
    public static final RegistrySupplier<Item> BLOOD_ROSE_PETAL = ITEMS.register("blood_rose_petal",
        () -> new Item(new Item.Properties()));
    public static final RegistrySupplier<LotusSeedsItem> LOTUS_SEEDS = ITEMS.register("lotus_seeds",
        LotusSeedsItem::new);
    public static final RegistrySupplier<LotusBlossomItem> LOTUS_BLOSSOM = ITEMS.register("lotus_blossom",
        LotusBlossomItem::new);

    // --- Bean system ---
    public static final RegistrySupplier<ItemBean> BEAN = ITEMS.register("bean", ItemBean::new);
    public static final RegistrySupplier<ItemLesserMagicBean> LESSERBEAN = ITEMS.register("lesserbean", ItemLesserMagicBean::new);
    public static final RegistrySupplier<ItemMagicBean> MAGICBEAN = ITEMS.register("magicbean", ItemMagicBean::new);
    public static final RegistrySupplier<ItemBeanStew> BEANSTEW = ITEMS.register("beanstew", ItemBeanStew::new);
    public static final RegistrySupplier<Item> GOLDEN_EGG = ITEMS.register("golden_egg",
        () -> new GoldenEggItem(new Item.Properties().stacksTo(16)));
    public static final RegistrySupplier<BlockItem> BEANSPROUT = ITEMS.register("beansprout",
        () -> new BlockItem(ModBlocks.BEANSPROUT.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> BEANSTALK = ITEMS.register("beanstalk",
        () -> new BlockItem(ModBlocks.BEANSTALK.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> SPECIALBEANSTALK = ITEMS.register("specialbeanstalk",
        () -> new BlockItem(ModBlocks.SPECIALBEANSTALK.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> BEANPOD = ITEMS.register("beanpod",
        () -> new BlockItem(ModBlocks.BEANPOD.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> PITCHER_PLANT = ITEMS.register("pitcher_plant",
        () -> new BlockItem(ModBlocks.PITCHER_PLANT.get(), new Item.Properties()));

    // --- Misc decorative ---
    public static final RegistrySupplier<BlockItem> COMPRESSED_SLIME_BLOCK = ITEMS.register("compressed_slime_block",
        () -> new BlockItem(ModBlocks.COMPRESSED_SLIME_BLOCK.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> TRIGGER_GLASS = ITEMS.register("trigger_glass",
        () -> new BlockItem(ModBlocks.TRIGGER_GLASS.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> LAPIS_LAMP = ITEMS.register("lapis_lamp",
        () -> new BlockItem(ModBlocks.LAPIS_LAMP.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> QUARTZ_LAMP = ITEMS.register("quartz_lamp",
        () -> new BlockItem(ModBlocks.QUARTZ_LAMP.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> ANCIENT_BRICK = ITEMS.register("ancient_brick",
        () -> new BlockItem(ModBlocks.ANCIENT_BRICK.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> FERTILIZED_DIRT = ITEMS.register("fertilized_dirt",
        () -> new BlockItem(ModBlocks.FERTILIZED_DIRT.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> PLATFORM_OAK = ITEMS.register("platform_oak",
        () -> new BlockItem(ModBlocks.PLATFORM_OAK.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> PLATFORM_SPRUCE = ITEMS.register("platform_spruce",
        () -> new BlockItem(ModBlocks.PLATFORM_SPRUCE.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> PLATFORM_BIRCH = ITEMS.register("platform_birch",
        () -> new BlockItem(ModBlocks.PLATFORM_BIRCH.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> PLATFORM_JUNGLE = ITEMS.register("platform_jungle",
        () -> new BlockItem(ModBlocks.PLATFORM_JUNGLE.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> PLATFORM_ACACIA = ITEMS.register("platform_acacia",
        () -> new BlockItem(ModBlocks.PLATFORM_ACACIA.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> PLATFORM_DARKOAK = ITEMS.register("platform_darkoak",
        () -> new BlockItem(ModBlocks.PLATFORM_DARKOAK.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> BLOCK_OF_STICKS = ITEMS.register("block_of_sticks",
        () -> new BlockItem(ModBlocks.BLOCK_OF_STICKS.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> BLOCK_OF_STICKS_RETURNING = ITEMS.register("block_of_sticks_returning",
        () -> new BlockItem(ModBlocks.BLOCK_OF_STICKS_RETURNING.get(), new Item.Properties()));
    public static final RegistrySupplier<BlockItem> PEACE_CANDLE = ITEMS.register("peace_candle",
        () -> new BlockItem(ModBlocks.PEACE_CANDLE.get(), new Item.Properties()));

    // --- Divining rods ---
    private static java.awt.Color[] rodColor(int r, int g, int b) {
        return new java.awt.Color[]{new java.awt.Color(r, g, b, 50)};
    }

    public static final RegistrySupplier<DiviningRodItem> DIVINING_ROD_COAL = ITEMS.register("divining_rod_coal",
        () -> new DiviningRodItem(new Item.Properties(), rodColor(20, 20, 20), new String[]{"minecraft:coal_ores"}));
    public static final RegistrySupplier<DiviningRodItem> DIVINING_ROD_IRON = ITEMS.register("divining_rod_iron",
        () -> new DiviningRodItem(new Item.Properties(), rodColor(211, 180, 159), new String[]{"minecraft:iron_ores"}));
    public static final RegistrySupplier<DiviningRodItem> DIVINING_ROD_GOLD = ITEMS.register("divining_rod_gold",
        () -> new DiviningRodItem(new Item.Properties(), rodColor(246, 233, 80), new String[]{"minecraft:gold_ores"}));
    public static final RegistrySupplier<DiviningRodItem> DIVINING_ROD_LAPIS = ITEMS.register("divining_rod_lapis",
        () -> new DiviningRodItem(new Item.Properties(), rodColor(5, 45, 150), new String[]{"minecraft:lapis_ores"}));
    public static final RegistrySupplier<DiviningRodItem> DIVINING_ROD_REDSTONE = ITEMS.register("divining_rod_redstone",
        () -> new DiviningRodItem(new Item.Properties(), rodColor(211, 1, 1), new String[]{"minecraft:redstone_ores"}));
    public static final RegistrySupplier<DiviningRodItem> DIVINING_ROD_EMERALD = ITEMS.register("divining_rod_emerald",
        () -> new DiviningRodItem(new Item.Properties(), rodColor(0, 220, 0), new String[]{"minecraft:emerald_ores"}));
    public static final RegistrySupplier<DiviningRodItem> DIVINING_ROD_DIAMOND = ITEMS.register("divining_rod_diamond",
        () -> new DiviningRodItem(new Item.Properties(), rodColor(87, 221, 229), new String[]{"minecraft:diamond_ores"}));
    public static final RegistrySupplier<DiviningRodItem> DIVINING_ROD_VANILLA = ITEMS.register("divining_rod_vanilla",
        () -> new DiviningRodItem(new Item.Properties(), new java.awt.Color[]{
            new java.awt.Color(20, 20, 20, 50), new java.awt.Color(211, 180, 159, 50), new java.awt.Color(246, 233, 80, 50),
            new java.awt.Color(5, 45, 150, 50), new java.awt.Color(211, 1, 1, 50), new java.awt.Color(0, 220, 0, 50),
            new java.awt.Color(87, 221, 229, 50)
        }, new String[]{"minecraft:coal_ores", "minecraft:iron_ores", "minecraft:gold_ores", "minecraft:lapis_ores",
            "minecraft:redstone_ores", "minecraft:emerald_ores", "minecraft:diamond_ores"}));

    // 16 stained-brick + 16 luminous-stained-brick + 16 luminous-block + 16 translucent-luminous colour variants.
    static {
        for (DyeColor c : DyeColor.values()) {
            String suffix = "_" + c.getName();
            ITEMS.register("stained_brick" + suffix,
                () -> new StainedBrickItem(ModBlocks.STAINED_BRICK.get(), new Item.Properties(), c));
            ITEMS.register("luminous_stained_brick" + suffix,
                () -> new StainedBrickItem(ModBlocks.LUMINOUS_STAINED_BRICK.get(), new Item.Properties(), c));
            ITEMS.register("luminous_block" + suffix,
                () -> new LuminousBlockItem(ModBlocks.LUMINOUS_BLOCK.get(), new Item.Properties(), c));
            ITEMS.register("translucent_luminous_block" + suffix,
                () -> new LuminousBlockItem(ModBlocks.TRANSLUCENT_LUMINOUS_BLOCK.get(), new Item.Properties(), c));
        }
    }

    // --- Standalone player items ---
    public static final RegistrySupplier<LavaCharmItem> LAVA_CHARM = ITEMS.register("lava_charm",
        () -> new LavaCharmItem(new Item.Properties()));

    public static final RegistrySupplier<WaterWalkingBootsItem> WATER_WALKING_BOOTS = ITEMS.register("water_walking_boots",
        () -> new WaterWalkingBootsItem(new Item.Properties()));

    public static final RegistrySupplier<LavaWadersItem> LAVA_WADERS = ITEMS.register("lava_waders",
        () -> new LavaWadersItem(new Item.Properties()));

    public static final RegistrySupplier<SuperLubricentBootsItem> SUPER_LUBRICENT_BOOTS = ITEMS.register("superlubricentboots",
        () -> new SuperLubricentBootsItem(new Item.Properties()));

    public static final RegistrySupplier<ObsidianSkullItem> OBSIDIAN_SKULL = ITEMS.register("obsidian_skull",
        () -> new ObsidianSkullItem(new Item.Properties()));

    public static final RegistrySupplier<PortkeyItem> PORTKEY = ITEMS.register("portkey",
        () -> new PortkeyItem(new Item.Properties().stacksTo(1)));

    private ModItems() {
    }

    public static void register() {
        ITEMS.register();
        TABS.register();
    }
}
